type: Sqlite # Avaiable types: mysql, sqlite

SQL:
  connection-string: "jdbc:sqlite:plugins/VDiscordIntegration/database.db"
  username: "username" # Not required for sqlite
  password: "password" # Not required for sqlite


